### PR TITLE
Adds optionable support for obeying robots.txt

### LINKED ISSUE #11: Any way to automatically obey robots.txt?
I guess I could load the robots.txt file of a site but is there a way to turn this on so that it will always follow the rules?

### PR DESCRIPTION
**Pull request by buren**
Usage:
 
```ruby
# To have this work add "gem 'robots', '~> 0.1'" to Gemfile
Spidr.site(
  'http://matasano.com/',
  :robots => true
)
```
Closes #11

### CODE REVIEW

**Comment by postmodern** [comment]
Eh, I prefer to ignore `robots.txt` and spider everything. I do like the idea of providing the option though. Instead of adding it to `allowed_links`, I think it should be added to [Spidr::Agent#visit?](https://github.com/postmodern/spidr/blob/00f0ff1864d56bad1352aa43a925bc645f777351/lib/spidr/agent.rb#L749-L757).

**Comment by buren** [comment]
Something like e2c2883? Its not finished yet, I haven't added any tests yet. Just wanted to get your feedback first :)

**Comment by postmodern** [comment]
Yeah, but get rid of the NoRobots null object. Just do a `@robots && @robots.allow?(uri)`. Note that [Robots#allowed?](https://github.com/fizx/robots/blob/098390222ec048e7e00fefa081f83f1cf9e67511/lib/robots.rb#L125) accepts URIs. Also, should robots be all or nothing, or configurable per host?

**Comment by buren** [comment]
I removed the null object, and did `@robots ? @robots.allowed?(uri) : true` to have it return true if `options[:robots]` is falsy. 

My guess is that in most cases you would either respect it for all hosts or just ignore robots.txt completely. What do you think?

**Pull request merged**
