### PR TITLE
Doc: Syntax highlight code blocks

### PR DESCRIPTION
**Pull request by vfonic**

### CODE REVIEW

**Comment by postmodern** [comment]
Arg, this may break YARD/kramdown. Both [YARD][1] and [kramdown][2] support GitHub Flavored Markdown (GFM), but in different ways. Also, the [official documentation](https://github.com/postmodern/spidr) is already syntax highlighted.

[1]: https://github.com/lsegal/yard/blob/master/docs/WhatsNew.md#github-flavoured-markdown-now-works-out-of-box-074
[2]: https://kramdown.gettalong.org/parser/gfm.html

**Comment by vfonic** [comment]
Ah, I see.

For me the official documentation is not syntax highlighted. It's just in a code block, but there's no syntax highlighting, hence the PR.

Which other websites is this Readme rendered on, where this change affects it negatively?

**Comment by postmodern** [comment]
I think I screwed up the official documentation link. Should have been: https://www.rubydoc.info/gems/spidr#Examples which does have syntax highlighting.

**Comment by vfonic** [comment]
You're right. Oh well, I'll close the PR then.

**Pull request closed without merging**
